---
version: '3.7'

services:
  pmm-server-encryption:
    image: ${PMM_SERVER_IMAGE:-perconalab/pmm-server:3-dev-latest}
    container_name: pmm-server-encryption
    ports:
      - '8082:8080'
      - '8445:8443'
    environment:
      - PMM_DEBUG=1
      - PMM_ENCRYPTION_KEY_PATH=/srv/non-default.key
