version: '3.8'
services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:13-alpine}
    container_name: postgres_ssl
    command: >
      -c shared_preload_libraries=pg_stat_statements
      -c track_activity_query_size=2048
      -c pg_stat_statements.max=10000
      -c pg_stat_monitor.pgsm_query_max_len=10000
      -c pg_stat_monitor.pgsm_normalized_query=0
      -c pg_stat_statements.track=all
      -c pg_stat_statements.save=off
      -c track_io_timing=on
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server-crt.pem
      -c ssl_key_file=/var/lib/postgresql/server-key.pem
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${PWD}/testdata/mysql/ssl-cert-scripts/certs/:/var/lib/postgresql