module.exports = {
  url: 'graph/d/node-instance-overview/nodes-overview?orgId=1&refresh=1m',
  metrics: [
    // Overview
    'Nodes',
    'Min Node Uptime',
    'DB Instances',
    'Min DB Uptime',
    'Total Virtual CPUs',
    'Total RAM',
    'Virtual Memory Total',
    'Disk Space Total',
    // Environment Details
    'Regions',
    'Types',
    'Nodes',
    'Regions',
    'Service Types',
    'Services',
    // CPU
    'Top Usage',
    'Top Steal',
    'Top I/O Wait',
    'Top Saturation',
    'Top Switches',
    'Top Load',
    'Top Runnable Procs',
    'Top Blocked Procs',
    // CPU Details
    'Top 5 CPU Usage',
    'CPU Usage',
    'Top 5 CPU Steal',
    'CPU Steal',
    'Top 5 CPU I/O Wait',
    'CPU I/O Wait',
    'Top 5 CPU Saturation',
    'CPU Saturation',
    'Top 5 Context Switches',
    'Switches',
    'Top 5 Runnable Processes',
    'Runnable Processes',
    'Top 5 Blocked Processes',
    'Blocked Processes',
    // Memory
    'Min Memory Available',
    'Min Virtual Memory Available',
    'Top File Cache Active Memory',
    'Min Swap Available',
    'Top Swap Reads',
    'Top Swap Writes',
    // Memory & Swap Details
    'Free Memory Percent',
    'Available Virtual Memory Percent',
    'Free Swap Space Percent',
    'Top 5 Used Memory',
    'Top 5 Free Memory',
    'Top 5 Used Virtual Memory',
    'Top 5 Available Virtual Memory',
    'Top 5 Used Swap Space',
    'Top 5 Free Swap Space',
    'Top 5 Swap In (Reads)',
    'Top 5 Swap Out (Writes)',
    // Disk
    'Min Free Space Available',
    'Top I/O Load',
    'Top Disk Latency',
    'Top Disk Operations',
    'Top Disk Bandwidth',
    'Top I/O Activity',
    // Disk Details
    'Top 5 Disk I/O Load',
    'Disk I/O Load',
    'Top 5 Disk Latency',
    'Disk Latency',
    'Top 5 Disk Bandwidth',
    'Disk Bandwidth',
    'Top 5 I/O Activity',
    'I/O Activity',
    // Network
    'Top Receive Network Traffic',
    'Top Transmit Network Traffic',
    'Top Errors',
    'Top Drop',
    'Top Retransmission',
    'Top Retransmit rate',
    // Network Details.
    'Top 5 Network Traffic',
    'Network Traffic',
    'Top 5 Local Network Errors',
    'Errors',
    'Top 5 TCP Retransmission',
    'Retransmission',
    'Top 5 Local Network Drop',
    'Drop',
  ],
};

// module.exports = nodeOverviewDashboard;
// export default nodeOverviewDashboard;
