---
version: '3.7'

volumes:
  scrape-intervals-pmm-server-data:

networks:
  scrape-intervals:

services:
  pmm-server-scrape-intervals:
    image: ${DOCKER_VERSION:-perconalab/pmm-server:dev-latest}
    container_name: pmm-server-scrape-intervals
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1/ping" ]
      interval: 3s
      timeout: 2s
      retries: 20
    ports:
      - "180:80"
      - "1443:443"
    environment:
      - PMM_DEBUG=1
    volumes:
      - scrape-intervals-pmm-server-data:/srv
    networks:
      - scrape-intervals

  pmm-client-scrape-intervals:
    image: ${CLIENT_DOCKER_VERSION:-perconalab/pmm-client:dev-latest}
    container_name: pmm-client-scrape-intervals
    depends_on:
      pmm-server-scrape-intervals:
        condition: service_healthy
    environment:
      - PMM_AGENT_SETUP=1
      - PMM_AGENT_SERVER_ADDRESS=pmm-server-scrape-intervals
      - PMM_AGENT_SERVER_USERNAME=admin
      - PMM_AGENT_SERVER_PASSWORD=admin
      - PMM_AGENT_PORTS_MIN=41000
      - PMM_AGENT_PORTS_MAX=41500
      - PMM_AGENT_SERVER_INSECURE_TLS=1
      - PMM_AGENT_CONFIG_FILE=config/pmm-agent.yaml
      - PMM_AGENT_SETUP_NODE_NAME=pmm-client-scrape-intervals
      - PMM_AGENT_SETUP_FORCE=1
      - PMM_AGENT_SETUP_NODE_TYPE=container
    restart: on-failure
    networks:
      - scrape-intervals
