---
name: pmm2-ui-tests-matrix

on:
  # run with default inputs
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: "Target branch for pmm-ui-tests repository"
        default: 'main' 
        required: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      SHA: ${{ github.event.inputs.sha || 'null' }}

      UI_TESTS_TAG: ${{ github.event.inputs.pmm_ui_tests_tag }}
      UI_TESTS_BRANCH: ${{ github.event.inputs.ui_tests_branch }}
      OAUTH_ISSUER_URL: 'https://id-dev.percona.com/oauth2/aus15pi5rjdtfrcH51d7'

    steps:
      - name: Trigger pmm-ui-Tests for ia
        uses: percona-platform/workflow-dispatch@v1
        with:
          workflow: pmm2-ui-tests
          token: ${{ secrets.ROBOT_TOKEN }}
          repo: percona/pmm-ui-tests
          ref: main
          inputs: |
            {
                "pmm_ui_tests_branch": "main",
                "pmm_ui_tests_tag": "@ia",
            }

      - name: Trigger pmm-ui-Tests for instances
        uses: percona-platform/workflow-dispatch@v1
        with:
          workflow: pmm2-ui-tests
          token: ${{ secrets.ROBOT_TOKEN }}
          repo: percona/pmm-ui-tests
          ref: main
          inputs: |
            {
                "pmm_ui_tests_branch": "main",
                "pmm_ui_tests_tag": "@instances",
            }
