name: "PMM Upgrade Matrix (e2e tests)"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: 'pmm-ui-tests repository branch'
        default: 'main'
        required: true
      pmm_qa_branch:
        description: 'pmm-qa repository branch(for setup)'
        default: 'main'
        required: true
      upgrade_type:
        description: 'Upgrade way:'
        required: true
        default: 'UI way'
        type: choice
        options:
          - UI way
          - Docker way
      repository:
        description: 'Upgrade to:'
        required: true
        default: 'dev-latest'
        type: choice
        options:
          - release
          - release candidate
          - dev-latest
  push:
    branches:
      - PMM-7-update-action-update

jobs:
  upgrade-tests:
    name: 'Upgrade'
    uses: ./.github/workflows/pmm-ui-tests-matrix-upgrade.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        old_version: [ 2.37.0, 2.36.0, 2.35.0, 2.34.0, 2.33.0 ]
    with:
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch }}
      pmm_server_start_version: ${{ matrix.old_version }}
      pmm_client_start_version: ${{ matrix.old_version }}
      upgrade_type: ${{ inputs.upgrade_type }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch }}
      repository: ${{ inputs.repository || 'release' }}
