name: PMM E2E Tests(Playwright)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: 'pmm-ui-tests repository branch'
        default: 'main'
        required: true
      pmm_qa_branch:
        description: 'pmm-qa repository branch(for setup)'
        default: 'main'
        required: true
      pmm_server_version:
        description: 'PMM Server version to upgrade (latest|dev-latest|x.xx.x|x.xx.x-rc)'
        default: 'dev-latest'
        required: true
      pmm_client_version:
        description: 'PMM Client version to upgrade from (dev-latest|pmm2-latest|pmm2-rc|x.xx.x)'
        default: 'dev-latest'
        required: true
jobs:
  inventory:
    name: Inventory
    uses: ./.github/workflows/ui-tests-pipeline.yml
    secrets: inherit
    with:
      pmm_ui_tests_branch: ${{ github.event.inputs.pmm_ui_tests_branch || github.head_ref || 'main '}}
      pmm_qa_branch: ${{ github.event.inputs.pmm_qa_branch || 'main' }}
      pmm_server_version: ${{ inputs.pmm_server_version || 'dev-latest' }}
      client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
      tags_for_playwright: '@inventory'
      client_flags: '--addclient=modb,1 --addclient=ps,1 --addclient=pdpgsql,1'
      version_string: ${{ inputs.pmm_server_version || 'dev-latest' }}

  portal:
    name: Portal
    uses: ./.github/workflows/ui-tests-pipeline.yml
    secrets: inherit
    with:
      pmm_ui_tests_branch: ${{ github.event.inputs.pmm_ui_tests_branch || github.head_ref || 'main '}}
      pmm_qa_branch: ${{ github.event.inputs.pmm_qa_branch || 'main' }}
      pmm_server_version: ${{ inputs.pmm_server_version || 'dev-latest' }}
      client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
      tags_for_playwright: '@portal'
      client_flags: ''
      version_string: ${{ inputs.pmm_server_version || 'dev-latest' }}

  rbac:
    name: RBAC
    uses: ./.github/workflows/ui-tests-pipeline.yml
    secrets: inherit
    with:
      pmm_ui_tests_branch: ${{ github.event.inputs.pmm_ui_tests_branch || github.head_ref || 'main '}}
      pmm_qa_branch: ${{ github.event.inputs.pmm_qa_branch || 'main' }}
      pmm_server_version: ${{ inputs.pmm_server_version || 'dev-latest' }}
      client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
      tags_for_playwright: '@rbac'
      client_flags: '--addclient=ps,1 --addclient=pdpgsql,1'
      version_string: ${{ inputs.pmm_server_version || 'dev-latest' }}
