name: PMM2 UI Tests Upgrade Matrix

on:
  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: 'pmm-ui-tests repository branch'
        default: 'main'
        required: true
      pmm_server_start_version:
        description: 'PMM Server version to upgrade (latest|dev-latest|x.xx.x|x.xx.x-rc)'
        default: 'latest'
        required: true
      pmm_client_start_version:
        description: 'PMM Client version to upgrade from (dev-latest|pmm2-latest|pmm2-rc|x.xx.x)'
        default: 'pmm2-latest'
        required: true
      pmm_qa_branch:
        description: 'pmm-qa repository branch(for setup)'
        default: 'main'
        required: true
      repository:
        description: 'Upgrade to:'
        required: true
        default: 'dev-latest'
        type: choice
        options:
          - release
          - release candidate
          - dev-latest

jobs:
  general:
    name: General
    uses: ./.github/workflows/pmm-ui-tests-upgrade.yml
    secrets: inherit
    with:
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
      pre_upgrade_tests: '@pre-upgrade'
      post_upgrade_tests: ''
      pmm_server_start_version: ${{ inputs.pmm_server_start_version || 'latest' }}
      pmm_client_start_version: ${{ inputs.pmm_client_start_version || 'pmm2-latest' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      services_list: ''
      repository: ${{ inputs.repository }}

  rbac:
    name: RBAC
    uses: ./.github/workflows/pmm-ui-tests-upgrade.yml
    secrets: inherit
    with:
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
      pre_upgrade_tests: '@rbac-pre-upgrade'
      post_upgrade_tests: '@rbac-post-upgrade'
      pmm_server_start_version: ${{ inputs.pmm_server_start_version || 'latest' }}
      pmm_client_start_version: ${{ inputs.pmm_client_start_version || 'pmm2-latest' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      services_list: '--addclient=ps,1 --addclient=pdpgsql,1'
      repository: ${{ inputs.repository }}

  portal:
    name: Portal
    uses: ./.github/workflows/pmm-ui-tests-upgrade.yml
    secrets: inherit
    with:
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
      pre_upgrade_tests: '@pre-pmm-portal-upgrade'
      post_upgrade_tests: '@post-pmm-portal-upgrade'
      pmm_server_start_version: ${{ inputs.pmm_server_start_version || 'latest' }}
      pmm_client_start_version: ${{ inputs.pmm_client_start_version || 'pmm2-latest' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      services_list: ''
      repository: ${{ inputs.repository }}
