---
name: UI Tests Matrix

on:
  # run with default inputs
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: "Target branch for pmm-ui-tests repository"
        default: 'main' 
        required: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    env:
      UI_TESTS_BRANCH: ${{ github.event.inputs.ui_tests_branch }}
      OAUTH_ISSUER_URL: 'https://id-dev.percona.com/oauth2/aus15pi5rjdtfrcH51d7'

    steps:
      - name: Tests for ${{ github.event.inputs.branch || 'main' }} at ${{ github.event.inputs.repo || 'cicd' }} repo
        if: ${{ github.event_name == 'workflow_dispatch' && env.SHA != 'null' }}
        uses: percona-platform/github-status-action@v1
        with:
          context: 'PMM ui Tests'
          description: 'Tests execution has been started'
          state: 'pending'
          repository: ${{ github.event.inputs.repo }}
          target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          sha: ${{ env.SHA }}

      - name: Install NodeJS v16
        uses: percona-platform/setup-node@v2
        with:
          node-version: 16

      - name: Checkout UI tests
        uses: percona-platform/checkout@v2
        with:
          ref: ${{ env.UI_TESTS_BRANCH }}
          repository: percona/pmm-ui-tests
          path: ./pmm-ui-tests
      
      - name: which folder are we in 
        run: ls

      - name: Compose PMM-Sever
        run: |
          cd ./pmm-ui-tests
          docker-compose up -d

      - name: which folder are we in
        run: ls

      - name: Execute Tests
        run: |
          cd ./pmm-ui-tests
          npm install
          npx codeceptjs run --steps -c pr.codecept.js --grep '@portal'

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: pmm-ui-tests/tests/output/allure
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Attaching the report
        if: ${{ always() && steps.ui-tests.outcome != 'skipped' }}
        uses: percona-platform/upload-artifact@v2
        with:
          name: ui-tests-report
          path: allure-history

      - name: List Files
        run: |
          ls
          cd ./pmmm-ui-tests
          ls
