name: PMM2 UI Tests Upgrade Matrix

on:
  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: 'Target branch for pmm-ui-tests repository'
        default: 'main'
        required: true
      pmm_server_version:
        description: 'Version of the pmm server used for testing'
        default: 'dev-latest'
        required: true
      pmm_server_docker_tag:
        description: 'Use when tag different to: "perconalab/pmm-server" is required'
        type: string
      pmm_client_version:
        description: 'Version of the pmm client used for testing'
        default: 'dev-latest'
        required: true
      pmm_client_upgrade_version:
        description: 'Version of the pmm client to upgrade to, if left empty, then version based on repository will be selected.'
        type: string
      pmm_qa_branch:
        description: 'Branch for the pmm-qa repository.'
        default: 'main'
        required: true
      repository:
        description: 'Enable Selected Repository.'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - testing
        - experimental

jobs:
   rbac:
      name: RBAC
      uses: ./.github/workflows/pmm-ui-tests-upgrade.yml
      secrets: inherit
      with:
        pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
        pmm_pre_upgrade_flag: '@rbac-pre-upgrade'
        pmm_post_upgrade_flag: '@rbac-post-upgrade'
        pmm_server_version: ${{ inputs.pmm_server_version || 'dev-latest' }}
        pmm_server_docker_tag: ${{ inputs.pmm_server_docker_tag }}
        pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
        pmm_client_upgrade_version: ${{ inputs.pmm_client_upgrade_version }}
        pmm_clients: '--addclient=ps,1 --addclient=pdpgsql,1'
        pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
        repository: ${{ inputs.repository }}

   portal:
      name: Portal
      uses: ./.github/workflows/pmm-ui-tests-upgrade.yml
      secrets: inherit
      with:
        pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
        pmm_pre_upgrade_flag: '@pre-pmm-portal-upgrade'
        pmm_post_upgrade_flag: '@post-pmm-portal-upgrade'
        pmm_server_version: ${{ inputs.pmm_server_version || 'dev-latest' }}
        pmm_server_docker_tag: ${{ inputs.pmm_server_docker_tag }}
        pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
        pmm_client_upgrade_version: ${{ inputs.pmm_client_upgrade_version }}
        pmm_clients: ''
        pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
        repository: ${{ inputs.repository }}

   configuration:
     name: 'Configuration / Settings'
     uses: ./.github/workflows/pmm-ui-tests-upgrade.yml
     secrets: inherit
     with:
       pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
       pmm_pre_upgrade_flag: '@config-pre-upgrade'
       pmm_post_upgrade_flag: '@config-post-upgrade'
       pmm_server_version: ${{ inputs.pmm_server_version || 'dev-latest' }}
       pmm_server_docker_tag: ${{ inputs.pmm_server_docker_tag }}
       pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
       pmm_client_upgrade_version: ${{ inputs.pmm_client_upgrade_version }}
       pmm_clients: ''
       pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
       repository: ${{ inputs.repository }}
