name: PMM2 UI Tests-Matrix

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: 'Target branch for pmm-ui-tests repository'
        default: 'main'
        required: true
      pmm_server_version:
        description: 'Version of the pmm server used for testing'
        default: 'dev-latest'
        required: true
      pmm_server_docker_tag:
        description: 'Use when tag different to: "perconalab/pmm-server" is required'
        type: string
      pmm_client_version:
        description: 'Version of the pmm client used for testing'
        default: 'dev-latest'
        required: true
      pmm_qa_branch:
        description: 'Branch for the pmm-qa repository.'
        default: 'main'
        required: true

jobs:
  rbac:
    name: RBAC
    uses: ./.github/workflows/pmm-ui-tests.yml
    secrets: inherit
    with:
      pmm_ui_tests_branch: ${{ github.event.inputs.pmm_ui_tests_branch || github.head_ref || 'main '}}
      pmm_test_flag: '@rbac'
      pmm_server_version: ${{ github.event.inputs.pmm_server_version || 'dev-latest' }}
      pmm_server_docker_tag: ${{ inputs.pmm_server_docker_tag }}
      pmm_client_version: ${{ github.event.inputs.pmm_client_version || 'dev-latest' }}
      pmm_clients: '--addclient=ps,1 --addclient=pdpgsql,1'
      pmm_qa_branch: ${{ github.event.inputs.pmm_qa_branch || 'main' }}

  portal:
    name: Portal
    uses: ./.github/workflows/pmm-ui-tests.yml
    secrets: inherit
    with:
      pmm_ui_tests_branch: ${{ github.event.inputs.pmm_ui_tests_branch || github.head_ref || 'main '}}
      pmm_test_flag: '@portal'
      pmm_server_version: ${{ github.event.inputs.pmm_server_version || 'dev-latest' }}
      pmm_server_docker_tag: ${{ inputs.pmm_server_docker_tag }}
      pmm_client_version: ${{ github.event.inputs.pmm_client_version || 'dev-latest' }}
      pmm_clients: ''
      pmm_qa_branch: ${{ github.event.inputs.pmm_qa_branch || 'main' }}

  inventory:
    name: Inventory
    uses: ./.github/workflows/pmm-ui-tests.yml
    secrets: inherit
    with:
      pmm_ui_tests_branch: ${{ github.event.inputs.pmm_ui_tests_branch || github.head_ref || 'main '}}
      pmm_test_flag: '@inventory'
      pmm_server_version: ${{ github.event.inputs.pmm_server_version || 'dev-latest' }}
      pmm_server_docker_tag: ${{ inputs.pmm_server_docker_tag }}
      pmm_client_version: ${{ github.event.inputs.pmm_client_version || 'dev-latest' }}
      pmm_clients: '--addclient=modb,1'
      pmm_qa_branch: ${{ github.event.inputs.pmm_qa_branch || 'main' }}

  advisors:
    name: Advisors
    uses: ./.github/workflows/pmm-ui-tests.yml
    secrets: inherit
    with:
      pmm_ui_tests_branch: ${{ github.event.inputs.pmm_ui_tests_branch || github.head_ref || 'main '}}
      pmm_test_flag: '@advisors'
      pmm_server_version: ${{ github.event.inputs.pmm_server_version || 'dev-latest' }}
      pmm_server_docker_tag: ${{ inputs.pmm_server_docker_tag }}
      pmm_client_version: ${{ github.event.inputs.pmm_client_version || 'dev-latest' }}
      pmm_clients: '--addclient=psmodb,1 --addclient=modb,1 --addclient=ps,1 --addclient=pdpgsql,1 --pdpgsql-version=14 --mo-version=4.4.1 --ps-version=5.7  --psmo-version=3.6'
      pmm_qa_branch: ${{ github.event.inputs.pmm_qa_branch || 'main' }}

  developmentAdvisors:
    name: Advisors
    uses: ./.github/workflows/pmm-ui-tests.yml
    secrets: inherit
    env:
      WORKSPACE: ${{ github.workspace }}
    with:
      pmm_ui_tests_branch: ${{ github.event.inputs.pmm_ui_tests_branch || github.head_ref || 'main '}}
      pmm_test_flag: '@developmentAdvisors'
      pmm_server_version: ${{ github.event.inputs.pmm_server_version || 'dev-latest' }}
      pmm_server_docker_tag: ${{ inputs.pmm_server_docker_tag }}
      pmm_client_version: ${{ github.event.inputs.pmm_client_version || 'dev-latest' }}
      pmm_clients: '--addclient=ps,1 --pmm-server-flags="-e PERCONA_TEST_CHECKS_FILE=/opt/checks/replica_set_test_advisor.yml" --mongo-replica-for-backup --ps-version=5.7'
      pmm_qa_branch: ${{ github.event.inputs.pmm_qa_branch || 'main' }}
    
