---
name: UI Tests Matrix

on:
  # run with default inputs
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: "Target branch for pmm-ui-tests repository"
        default: 'main' 
        required: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    env:
      UI_TESTS_BRANCH: ${{ github.event.inputs.ui_tests_branch }}
      OAUTH_ISSUER_URL: 'https://id-dev.percona.com/oauth2/aus15pi5rjdtfrcH51d7'

    steps:
      - name: Tests for ${{ github.event.inputs.branch || 'main' }} at ${{ github.event.inputs.repo || 'cicd' }} repo
        if: ${{ github.event_name == 'workflow_dispatch' && env.SHA != 'null' }}
        uses: percona-platform/github-status-action@v1
        with:
          context: 'PMM ui Tests'
          description: 'Tests execution has been started'
          state: 'pending'
          repository: ${{ github.event.inputs.repo }}
          target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          sha: ${{ env.SHA }}

      - name: Checkout UI tests
        uses: percona-platform/checkout@v2
        with:
          ref: ${{ env.UI_TESTS_BRANCH }}
          repository: percona/pmm-ui-tests
          path: ./pmm-ui-tests
      
      - name: which folder are we in 
        run: ls

      - name: Compose PMM-Sever
        run: |
          cd ./pmm-ui-tests
          docker-compose up -d
