name: "Portal Tests Matrix"

on:
  push:
    branches:
      - PMM-7-update-gh
  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: 'pmm-ui-tests repository branch'
        default: 'main'
        required: true
      pmm_qa_branch:
        description: 'pmm-qa repository branch(for setup)'
        default: 'main'
        required: true

jobs:
  get_versions:
    name: Get versions
    uses: ./.github/workflows/pmm-version-getter.yml
    with:
      repository: ${{ inputs.repository || 'dev-latest'}}
      matrix_range: 5

  portal:
    name: 'Portal / Integration'
    uses: ./.github/workflows/pmm-ui-tests.yml
    secrets: inherit
    needs: get_versions
    strategy:
      fail-fast: false
      matrix:
        old_version: ${{ fromJSON(needs.get_versions.outputs.version_matrix) }}
        include:
          - old_version: dev-latest
    with:
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'PMM-7-update-gh' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_server_version: ${{ matrix.old_version }}
      client_version: ${{ matrix.old_version }}
      tags_for_playwright: '@portal'
      client_flags: ''
      version_string: ${{needs.get_versions.outputs.start_version}}
